version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TICKETMASTER_API_KEY=${TICKETMASTER_API_KEY}
      - MEETUP_API_KEY=${MEETUP_API_KEY}
      - SEATGEEK_API_KEY=${SEATGEEK_API_KEY}
      - VIVIDSEATS_API_KEY=${VIVIDSEATS_API_KEY}
    volumes:
      - .:/app
    command: python -m src.app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080 